import html

import streamlit as st

from src.ticket_manager import TicketManager


def _safe_title(value):
    """
    Safely convert ticket values to title case.
    """

    if value is None or value == "":
        return "Unknown"

    return str(value).title()


def _count_tickets(tickets, field, value):
    """
    Count tickets matching a field value.
    Case-insensitive.
    """

    return sum(
        1
        for ticket in tickets
        if str(
            ticket.get(field, "")
        ).lower() == value.lower()
    )


def _get_priority_class(priority):
    """
    Return CSS class for ticket priority.
    """

    priority = str(priority).lower().strip()

    priority_classes = {
        "critical": "resolve-priority-critical",
        "high": "resolve-priority-high",
        "medium": "resolve-priority-medium",
        "low": "resolve-priority-low",
    }

    return priority_classes.get(
        priority,
        "resolve-priority-default",
    )


def _get_status_class(status):
    """
    Return CSS class for ticket status.
    """

    status = str(status).lower().strip()

    status_classes = {
        "open": "resolve-status-open",
        "in progress": "resolve-status-progress",
        "resolved": "resolve-status-resolved",
    }

    return status_classes.get(
        status,
        "resolve-status-default",
    )

def render_ticket_dashboard():
    """
    Render ResolveAI premium ticket workspace.
    """

    manager = TicketManager()

    all_tickets = manager.get_all_tickets()

    # =====================================================
    # EMPTY STATE
    # =====================================================

    if not all_tickets:

        st.markdown(
            """
<div class="resolve-ticket-empty">
<div class="resolve-ticket-empty-icon">◇</div>
<div class="resolve-ticket-empty-title">
No support tickets yet
</div>
<div class="resolve-ticket-empty-text">
Tickets generated by ResolveAI will appear here.
</div>
</div>
""",
            unsafe_allow_html=True,
        )

        return

    # =====================================================
    # TICKET STATISTICS
    # =====================================================

    total_tickets = len(all_tickets)

    open_tickets = _count_tickets(
        all_tickets,
        "status",
        "open",
    )

    resolved_tickets = _count_tickets(
        all_tickets,
        "status",
        "resolved",
    )

    critical_tickets = _count_tickets(
        all_tickets,
        "priority",
        "critical",
    )

    st.markdown(
        '<div class="resolve-label">'
        'TICKET OVERVIEW'
        '</div>',
        unsafe_allow_html=True,
    )

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "Total Tickets",
            total_tickets,
        )

    with col2:
        st.metric(
            "Open",
            open_tickets,
        )

    with col3:
        st.metric(
            "Critical",
            critical_tickets,
        )

    with col4:
        st.metric(
            "Resolved",
            resolved_tickets,
        )

    st.markdown("<br>", unsafe_allow_html=True)

    # =====================================================
    # SEARCH + FILTER
    # =====================================================

    st.markdown(
        '<div class="resolve-label">'
        'TICKET QUEUE'
        '</div>',
        unsafe_allow_html=True,
    )

    # =====================================================
    # SEARCH + FILTER + SORT
    # =====================================================

    search_col, status_col, priority_col, sort_col = st.columns(
        [2.8, 1.2, 1.2, 1.3],
        gap="small",
    )

    with search_col:

        search = st.text_input(
            "Search",
            placeholder="Search tickets...",
            label_visibility="collapsed",
            key="ticket_search",
        )

    with status_col:

        status_filter = st.selectbox(
            "Status",
            [
                "All statuses",
                "Open",
                "In Progress",
                "Resolved",
            ],
            label_visibility="collapsed",
            key="ticket_status_filter",
        )

    with priority_col:

        priority_filter = st.selectbox(
            "Priority",
            [
                "All priorities",
                "Critical",
                "High",
                "Medium",
                "Low",
            ],
            label_visibility="collapsed",
            key="ticket_priority_filter",
        )

    with sort_col:

        sort_option = st.selectbox(
            "Sort",
            [
                "Newest first",
                "Oldest first",
                "Priority",
            ],
            label_visibility="collapsed",
            key="ticket_sort",
        )

    with search_col:

        search = st.text_input(
            "Search",
            placeholder=(
                "Search ticket ID, message, "
                "intent, priority or status..."
            ),
            label_visibility="collapsed",
        )

    with status_col:

        status_filter = st.selectbox(
            "Status",
            [
                "All statuses",
                "Open",
                "Resolved",
            ],
            label_visibility="collapsed",
        )

    # =====================================================
    # SEARCH
    # =====================================================

    if search:

        tickets = manager.search_tickets(
            search
        )

    else:

        tickets = list(all_tickets)


    # =====================================================
    # STATUS FILTER
    # =====================================================

    if status_filter != "All statuses":

        tickets = [
            ticket
            for ticket in tickets
            if str(
                ticket.get(
                    "status",
                    "",
                )
            ).lower()
            == status_filter.lower()
        ]


    # =====================================================
    # PRIORITY FILTER
    # =====================================================

    if priority_filter != "All priorities":

        tickets = [
            ticket
            for ticket in tickets
            if str(
                ticket.get(
                    "priority",
                    "",
                )
            ).lower()
            == priority_filter.lower()
        ]


    # =====================================================
    # SORTING
    # =====================================================

    if sort_option == "Newest first":

        tickets = list(
            reversed(tickets)
        )

    elif sort_option == "Oldest first":

        tickets = list(tickets)

    elif sort_option == "Priority":

        priority_order = {
            "critical": 0,
            "high": 1,
            "medium": 2,
            "low": 3,
        }

        tickets = sorted(
            tickets,
            key=lambda ticket: priority_order.get(
                str(
                    ticket.get(
                        "priority",
                        "",
                    )
                ).lower(),
                99,
            ),
        )

    # =====================================================
    # STATUS FILTER
    # =====================================================

    if status_filter != "All statuses":

        tickets = [
            ticket
            for ticket in tickets
            if str(
                ticket.get(
                    "status",
                    "",
                )
            ).lower()
            == status_filter.lower()
        ]

    # =====================================================
    # NO SEARCH RESULTS
    # =====================================================

    if not tickets:

        st.info(
            "No tickets match your current search or filter."
        )

        return

    # =====================================================
    # TICKET SELECTOR
    # =====================================================

    ticket_ids = [
        ticket.get(
            "ticket_id",
            "Unknown",
        )
        for ticket in tickets
    ]

    st.markdown(
        '<div class="resolve-label">'
        'OPEN TICKET'
        '</div>',
        unsafe_allow_html=True,
    )

    selected_ticket_id = st.selectbox(
        "Select Ticket",
        ticket_ids,
        label_visibility="collapsed",
        key="selected_support_ticket",
    )

    ticket = manager.get_ticket(
        selected_ticket_id
    )

    if not ticket:

        st.error(
            "Unable to load the selected ticket."
        )

        return
    selected_intent = _safe_title(
        ticket.get(
            "intent",
            "Unknown",
        )
    )

    selected_priority = _safe_title(
        ticket.get(
            "priority",
            "Unknown",
        )
    )

    st.markdown(
        f"""
    <div class="resolve-selected-context">
    <span>Currently viewing</span>
    <strong>{selected_ticket_id}</strong>
    <span>·</span>
    <span>{selected_intent}</span>
    <span>·</span>
    <span>{selected_priority} priority</span>
    </div>
    """,
        unsafe_allow_html=True,
    )
    
    # =====================================================
    # QUEUE SUMMARY
    # =====================================================

    visible_count = len(tickets)

    total_count = len(all_tickets)

    st.markdown(
        f"""
    <div class="resolve-queue-summary">
    <div>
    <span class="resolve-queue-count">
    {visible_count}
    </span>
    tickets shown
    </div>

    <div class="resolve-queue-total">
    {total_count} total
    </div>
    </div>
    """,
        unsafe_allow_html=True,
    )
        # =====================================================
    # TICKET QUEUE
    # =====================================================

    st.markdown("<br>", unsafe_allow_html=True)

    st.markdown(
        '<div class="resolve-label">'
        'RECENT TICKETS'
        '</div>',
        unsafe_allow_html=True,
    )

    # Table header
    header_col1, header_col2, header_col3, header_col4 = st.columns(
        [2.2, 1.4, 1.2, 1],
    )

    with header_col1:
        st.markdown(
            '<div class="resolve-queue-header">TICKET</div>',
            unsafe_allow_html=True,
        )

    with header_col2:
        st.markdown(
            '<div class="resolve-queue-header">ISSUE</div>',
            unsafe_allow_html=True,
        )

    with header_col3:
        st.markdown(
            '<div class="resolve-queue-header">PRIORITY</div>',
            unsafe_allow_html=True,
        )

    with header_col4:
        st.markdown(
            '<div class="resolve-queue-header">STATUS</div>',
            unsafe_allow_html=True,
        )


    # -----------------------------------------------------
    # Ticket rows
    # -----------------------------------------------------

    for queue_ticket in tickets:

        queue_ticket_id = queue_ticket.get(
            "ticket_id",
            "Unknown",
        )

        queue_intent = _safe_title(
            queue_ticket.get(
                "intent",
                "Unknown",
            )
        )

        queue_priority = _safe_title(
            queue_ticket.get(
                "priority",
                "Unknown",
            )
        )

        queue_status = _safe_title(
            queue_ticket.get(
                "status",
                "Unknown",
            )
        )

        row_col1, row_col2, row_col3, row_col4 = st.columns(
            [2.2, 1.4, 1.2, 1],
        )

        with row_col1:

            st.markdown(
                f"""
    <div class="resolve-queue-ticket">
    {queue_ticket_id}
    </div>
    """,
                unsafe_allow_html=True,
            )

        with row_col2:

            st.markdown(
                f"""
    <div class="resolve-queue-value">
    {queue_intent}
    </div>
    """,
                unsafe_allow_html=True,
            )

        with row_col3:
            priority_class = _get_priority_class(
                queue_priority
            )

            st.markdown(
                f"""
    <div class="resolve-queue-priority ">
    <span class="resolve-ticket-badge {priority_class}">
    {queue_priority}
    </span>
    </div>
    """,
                unsafe_allow_html=True,
            )

        with row_col4:
            status_class = _get_status_class(
                queue_status
            )

            st.markdown(
                f"""
    <div class="resolve-queue-status">
    <span class="resolve-ticket-badge {status_class}">
    {queue_status}
    </span>
    </div>
    """,
                unsafe_allow_html=True,
            )

        st.markdown(
            '<div class="resolve-queue-divider"></div>',
            unsafe_allow_html=True,
        )

    # =====================================================
    # SELECTED TICKET
    # =====================================================

    st.markdown("<br>", unsafe_allow_html=True)

    st.markdown(
        '<div class="resolve-label">'
        'SELECTED TICKET'
        '</div>',
        unsafe_allow_html=True,
    )

    ticket_id = ticket.get(
        "ticket_id",
        "Unknown",
    )

    status = _safe_title(
        ticket.get(
            "status",
            "Unknown",
        )
    )
    status_class = _get_status_class(status)

    priority = _safe_title(
        ticket.get(
            "priority",
            "Unknown",
        )
    )
    priority_class = _get_priority_class(priority)

    intent = _safe_title(
        ticket.get(
            "intent",
            "Unknown",
        )
    )

    sentiment = _safe_title(
        ticket.get(
            "sentiment",
            "Unknown",
        )
    )

    created_at = ticket.get(
        "created_at",
        "Unknown",
    )

    # =====================================================
    # TICKET HEADER
    # =====================================================

    ticket_header = f"""
    <div class="resolve-ticket-header">

    <div>
    <div class="resolve-ticket-id">
    {ticket_id}
    </div>

    <div class="resolve-ticket-created">
    Created {created_at}
    </div>
    </div>

    <div class="resolve-ticket-badge {status_class}">
    {status}
    </div>

    </div>
    """

    st.markdown(
        ticket_header,
        unsafe_allow_html=True,
    )
    # =====================================================
    # TICKET ACTIONS
    # =====================================================

    st.markdown(
        '<div class="resolve-label">'
        'TICKET ACTIONS'
        '</div>',
        unsafe_allow_html=True,
    )

    action_col1, action_col2 = st.columns(
        [3, 1],
        gap="small",
    )

    status_options = [
        "Open",
        "In Progress",
        "Resolved",
    ]

    current_status = str(
        ticket.get(
            "status",
            "Open",
        )
    ).title()

    if current_status not in status_options:
        current_status = "Open"

    with action_col1:

        new_status = st.selectbox(
            "Ticket Status",
            status_options,
            index=status_options.index(
                current_status
            ),
            key=f"ticket_status_{ticket_id}",
        )

    with action_col2:

        st.markdown(
            '<div class="resolve-action-button-space"></div>',
            unsafe_allow_html=True,
        )

        update_clicked = st.button(
            "Update Status",
            use_container_width=True,
            key=f"update_status_{ticket_id}",
        )


    if update_clicked:

        updated_ticket = manager.update_status(
            ticket_id,
            new_status,
        )

        if updated_ticket:

            st.toast(
                f"{ticket_id} updated to {new_status}"
            )

            st.session_state[
                "ticket_status_updated"
            ] = True

            st.rerun()

        else:

            st.error(
                "Unable to update ticket status."
            )

    # =====================================================
    # TICKET METADATA
    # =====================================================

    meta1, meta2, meta3 = st.columns(3)

    with meta1:

        priority_class = _get_priority_class(
            priority
        )

        st.markdown(
            '<div class="resolve-ticket-meta-label">'
            'PRIORITY'
            '</div>',
            unsafe_allow_html=True,
        )

        st.markdown(
            f"""
    <span class="resolve-ticket-badge {priority_class}">
    {priority}
    </span>
    """,
            unsafe_allow_html=True,
        )

    with meta2:

        st.markdown(
            '<div class="resolve-ticket-meta-label">'
            'INTENT'
            '</div>',
            unsafe_allow_html=True,
        )

        st.markdown(
            f'<div class="resolve-ticket-meta-value">'
            f'{intent}'
            f'</div>',
            unsafe_allow_html=True,
        )

    with meta3:

        st.markdown(
            '<div class="resolve-ticket-meta-label">'
            'SENTIMENT'
            '</div>',
            unsafe_allow_html=True,
        )

        st.markdown(
            f'<div class="resolve-ticket-meta-value">'
            f'{sentiment}'
            f'</div>',
            unsafe_allow_html=True,
        )

    st.divider()

        
    # =====================================================
    # CUSTOMER MESSAGE
    # =====================================================

    customer_message = html.escape(
        str(
            ticket.get(
                "customer_message",
                "No customer message available.",
            )
        )
    )

    customer_html = f"""
    <div class="resolve-detail-card">
    <div class="resolve-detail-card-header">
    <div class="resolve-detail-icon">◌</div>

    <div>
    <div class="resolve-detail-title">
    Customer Message
    </div>

    <div class="resolve-detail-caption">
    Original support request
    </div>
    </div>
    </div>

    <div class="resolve-detail-content">
    {customer_message}
    </div>
    </div>
    """

    st.markdown(
        customer_html,
        unsafe_allow_html=True,
    )


    # =====================================================
    # AI SUMMARY
    # =====================================================

    summary = html.escape(
        str(
            ticket.get("summary")
            or "No AI summary available."
        )
    )

    summary_html = f"""
    <div class="resolve-detail-card">
    <div class="resolve-detail-card-header">
    <div class="resolve-detail-icon">◇</div>

    <div>
    <div class="resolve-detail-title">
    AI Summary
    </div>

    <div class="resolve-detail-caption">
    ResolveAI understanding
    </div>
    </div>
    </div>

    <div class="resolve-detail-content">
    {summary}
    </div>
    </div>
    """

    st.markdown(
        summary_html,
        unsafe_allow_html=True,
    )


    # =====================================================
    # ESCALATION
    # =====================================================

    escalation_reason = ticket.get(
        "escalation_reason"
    )

    if escalation_reason:

        escalation_reason = html.escape(
            str(escalation_reason)
        )

        escalation_html = f"""
    <div class="resolve-detail-card resolve-detail-escalation">
    <div class="resolve-detail-card-header">
    <div class="resolve-detail-icon">!</div>

    <div>
    <div class="resolve-detail-title">
    Human Escalation
    </div>

    <div class="resolve-detail-caption">
    Agent attention required
    </div>
    </div>
    </div>

    <div class="resolve-detail-content">
    {escalation_reason}
    </div>
    </div>
    """

    else:

        escalation_html = """
    <div class="resolve-detail-card">
    <div class="resolve-detail-card-header">
    <div class="resolve-detail-icon">✓</div>

    <div>
    <div class="resolve-detail-title">
    Escalation
    </div>

    <div class="resolve-detail-caption">
    Resolution routing
    </div>
    </div>
    </div>

    <div class="resolve-detail-content resolve-detail-muted">
    No human escalation is currently required.
    </div>
    </div>
    """

    st.markdown(
        escalation_html,
        unsafe_allow_html=True,
    )